### ISSUE TITLE
I like work on  a new feature of your project!

### ISSUE THREAD

**Issue by masoudtabatabaei** [amiryxe/credit-card-input#1]
Hi Amir, I forked your project and I like to work on it, Is it possible to send pull request?

**Comment by amiryxe** [comment]
Yes sure. I will be happy

**Comment by masoudtabatabaei** [comment]
thanks dear amir, I send pull request on your project!

**Comment by masoudtabatabaei** [comment]
> Yes sure. I will be happy

thanks dear amir, I send pull request on your project!
